# Generated by Django 5.1 on 2024-08-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10)),
                ('birthdate', models.DateField()),
                ('department', models.CharField(choices=[('IT', 'IT'), ('Physics', 'Physics'), ('Comsci', 'Comsci')], default='IT', max_length=10)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
