# Generated by Django 5.0.7 on 2024-09-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pics',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
