# Generated by Django 5.0.7 on 2024-09-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_employee_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pics',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
