# Generated by Django 5.0.7 on 2024-09-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0004_userrole_remove_employee_pics_employee_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=10),
        ),
    ]
