# Generated by Django 5.0.7 on 2024-09-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0005_delete_userrole_remove_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pics',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
