# Generated by Django 5.0.7 on 2024-09-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0006_employee_pics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='pics',
            new_name='picture',
        ),
    ]
